trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk >=3.x'
  inputs:
    packageType: sdk
# workaround for 'UseDotNet@2 cant find sdk version matching 3.x #11569'
# https://github.com/microsoft/azure-pipelines-tasks/issues/11569
    version: 3.0.x
#   version: 3.x


- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: 'src/**/*.csproj'
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/bin'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: 'src/**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: PublishPipelineArtifact@1
  displayName: 'Publish artifacts (bin)'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/bin'
    artifact: 'bin'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    includesource: true
    includesymbols: true
    nobuild: true
    arguments: '--version-suffix CI-$(Build.BuildNumber)'
    projects: 'src/**/*.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/pkg'
- task: PublishPipelineArtifact@1
  displayName: 'Publish artifacts (pkg)'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/pkg'
    artifact: 'pkg'